# Generated by cucumber-sinatra. (2012-12-23 09:24:50 +0200)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', './server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'capybara-webkit'
require 'rspec'

Capybara.default_driver = :webkit
Capybara.app = Sinatra::Application.new

class CampaignerAppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  CampaignerAppWorld.new
end
