#!/bin/sh

gem install bundler
bundle install --without test

(export portResult=0
while [ $portResult -eq 0 ] # lets wait until sinatra takes port
do
  nc -z localhost 5000 1>/dev/null 2>&1; portResult=$?;
done
sleep 1
open "http://localhost:5000" )&

bundle exec ruby ./server.rb -p 5000
